### ISSUE TITLE
The docs page has a How to Contribute FAQ Guideline on how to join and make changes to the docs page

### ISSUE THREAD

**Issue by thecartercodes** [tm41m/tm41m.github.io#7]

**Comment by inwhanroh** [comment]
Could you specify what should go on here? Am I on the right track with how I created the page?

![Image](https://github.com/tm41m/tm41m.github.io/assets/90230726/29694186-4836-41f2-b812-8504b745ef3b)

**Comment by thecartercodes** [comment]
Haha, that's excellent. Let's have the structure be like this

```
Contributing -- This page gives general guidelines on picking up git issues, joining discord to ask questions etc. You can leave it blank for now
     -> Daikon -- Each subpage nested in "Contributing" is just a copy paste of the CONTRIBUTING file from the repo
     -> Scopuli
     -> tm41m.github.io
             etc.

```

So since we've only got `CONTRIBUTING` in `scopuli`, your work is done when you paste that into the subpage. I imagine we'll have some general guidelines available once me you and andrew have completed the process a few times... it's a bit informal atm
